### ISSUE TITLE
Make agent visible to LiDAR

### ISSUE THREAD

**Issue by sskorol** [robotics-upo/hunav_gazebo_wrapper#1]
Hi @noeperez, @roberottt,

I followed the instructions and set everything up on Humble with some modifications. So the agent is walking based on provided goals. That works.
On the other hand, I have a robot with LiDAR, IMU, and a camera. The problem I noticed is that the LiDAR scanner can't see an agent as an obstacle. The Nav2 planner won't be able to effectively plan paths when it can't see such obvious dynamic obstacles.

So my question is: how can I make a LiDAR see the simulated agent?

Thanks,
Sergey

**Comment by noeperez** [comment]
Hi Sergey,

You just need to change the type of lidar. Instead of the regular lidar,
you need to use the gpu_laser plugin of Gazebo. This way, the agents are
properly detected.

**Comment by sskorol** [comment]
@noeperez thanks. But where can I find it? I see it's available only for [ROS1 branches](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_plugins/src/gazebo_ros_gpu_laser.cpp) e.g. `noetic-devel`. But I don't see it in `foxy` or [ros2](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/src/gazebo_ros_ray_sensor.cpp) branches.
So basically, I used an official `ray_sensor`. And it doesn't work. Is it hardcoded somewhere? Can I change it in the code?

**Comment by sskorol** [comment]
@noeperez yeah, I saw this, but as I've already mentioned, I use ROS2 Humble. And it doesn't seem to be present among gazebo plugins anymore.

**Comment by noeperez** [comment]
The ros_ray_sensor should be valid. Try just to change the sensor type to "gpu_ray". 
Below, you can find an example of a laser that we are using successfully.
Anyway, we test everything in Foxy, I can not be sure about Humble. Hope it works. 

`<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="sick_tim571_gpulaser_gazebo" params="name ros_topic update_rate min_angle max_angle">
    <gazebo reference="${name}_link">
      <sensor type="gpu_ray" name="${name}">
        
        <update_rate>${update_rate}</update_rate>
        <visualize>true</visualize>
        <ray>
          <scan>
            <horizontal>
              
              <samples>${818*(max_angle - min_angle)/(270.0 * deg_to_rad)}</samples>
              <resolution>1</resolution> 
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.05</min>
            <max>25.0</max>
            <resolution>0.001</resolution>
          </range>
          
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin filename="libgazebo_ros_ray_sensor.so" name="gazebo_ros_sick_laser">
          <ros>
                <namespace>/${name}</namespace>
                <argument>~/out:=${ros_topic}</argument>
          </ros>
          
          <alwaysOn>true</alwaysOn>
          <updateRate>${update_rate}</updateRate>
          <frame_name>${name}_link</frame_name>
          
          <output_type>sensor_msgs/LaserScan</output_type>
        </plugin>
      </sensor>
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

</robot>`

**Comment by noeperez** [comment]
The ros_ray_sensor should be valid. Try just to change the sensor type to "gpu_ray".
Below, you can find an example of a laser that we are using successfully.
Anyway, we test everything in Foxy, I can not be sure about Humble. Hope it works.

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sick_tim571_gpulaser_gazebo" params="name ros_topic update_rate min_angle max_angle">
    <gazebo reference="${name}_link">
      <**sensor type="gpu_ray"** name="${name}">
        
        <update_rate>${update_rate}</update_rate>
        <visualize>true</visualize>
        <ray>
          <scan>
            <horizontal>
              
              <samples>${818*(max_angle - min_angle)/(270.0 * deg_to_rad)}</samples>
              <resolution>1</resolution> 
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.05</min>
            <max>25.0</max>
            <resolution>0.001</resolution>
          </range>
          
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        **<plugin filename="libgazebo_ros_ray_sensor.so"** name="gazebo_ros_sick_laser">
          <ros>
                <namespace>/${name}</namespace>
                <argument>~/out:=${ros_topic}</argument>
          </ros>
          
          <alwaysOn>true</alwaysOn>
          <updateRate>${update_rate}</updateRate>
          <frame_name>${name}_link</frame_name>
          
          <output_type>sensor_msgs/LaserScan</output_type>
        </plugin>
      </sensor>
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>
</robot>

**Comment by noeperez** [comment]
...
`<sensor type="gpu_ray" name="lidar">`
...
`<plugin filename="libgazebo_ros_ray_sensor.so" name="gazebo_ros_lidar">`
...

**Comment by sskorol** [comment]
Perfect, `gpu_ray` type did the trick. Thanks!

**Comment by sskorol** [comment]
Hi @Dharnish4,

I just followed all the error messages and applied corresponding fixes in code and configs. In short, there are issues with headers, missing deps, and ROS params reading format. I can give more details maybe later today. Or would just push changes to a separate humble branch.

**Comment by sskorol** [comment]
@Dharnish4 I apologies. Moving to a new apartment. Hope to finish it this week. I’ll post it as soon as I spawn my work environment.

**Comment by sskorol** [comment]
Here are the [changes](https://github.com/robotics-upo/hunav_sim/compare/master...sskorol:hunav_sim:humble?expand=1) in this repo. So that you know, you need to adjust the launch file depending on your own needs. For example, I disabled GPU as it didn't work for me. If you want to add your own model, take a look at `WorldGenerator.cpp`, line 196.

And here are [changes](https://github.com/robotics-upo/hunav_sim/compare/master...sskorol:hunav_sim:humble?expand=1) from `hunav_sim` repo. Note that if you want to change human config, you may want to adjust `config/agents.yaml`. I changed the map there, played with goals, radius, behaviors, etc.

**Comment by noeperez** [comment]
@sskorol thank you very much for your work. 
We will test in Humble soon and create a branch for this distro (or we'll merge it with the master if the changes are valid for Foxy too).

**Comment by sskorol** [comment]
It’s better to go with a separate branch as there were some API changes in ROS. So you can create a humble branch. And I’ll open PR to it.
