### ISSUE TITLE
gazebo collision error

### ISSUE THREAD

**Issue by Booooms** [robotics-upo/hunav_gazebo_wrapper#6]
I tried example_cafe.launch.py now with only jackal robot added from ubuntu20.04 foxy.
By the way, when I checked the gazebo collision, it looks like the collision is rotated in the y-axis. I wonder where you set the collision model. Where can i find it?

![collisionerror](https://github.com/robotics-upo/hunav_gazebo_wrapper/assets/69511762/c61702b5-0442-4707-9a71-59f1c1359807)

**Comment by noeperez** [comment]
Hi!
Yes, we were not capable of placing the collision of the human models in the correct place. Anyway we are not using the collision for moving the agents nor avoiding obstacles. We are using the positions of the model to detect and avoid collisions. On the robot side, we rely on the robot sensors to detect and avoid the humans.

**Comment by Booooms** [comment]
Thank you for your response. 
From my understanding, humans avoid using positions, and robots detect humans using sensor data, is that correct? Also, I'm concerned about collision models overlapping and potentially causing problems later, so I'd like to turn them off. How can I do that?

**Comment by noeperez** [comment]
Honestly, I do not know. 
What I can say is that we had not have problems with the collisions models at any case.
