### ISSUE TITLE
People stuck in the ground Cafe

### ISSUE THREAD

**Issue by masskro0** [robotics-upo/hunav_gazebo_wrapper#7]
Setup:
Ubuntu 22.04
ROS Humble

If I launch the cafe example using
```ros2 launch hunav_gazebo_wrapper example_cafe.launch.py```<br>
then all people are stuck in the ground and can't move. I don't see any error/warning messages in the terminal. According to the terminal, each person has a unique spawn point, but somehow in the sim, they all spawn in the same location.<br>

```ros2 node list``` reveals the following nodes:
```
/gazebo
/hunav_agent_manager
/hunav_evaluator_node
/hunav_gazebo_world_generator
/hunav_loader
```

Am I missing something?

**Comment by noeperez** [comment]
Hi @masskro0 
 I have just tested with last available versions of the code (HuNavSim and GazeboWrapper which I updated both 2 days ago) in the same setup (Ubuntu22 and ROS Humble) and  `example_cafe.launch.py` is working properly for me. 
 So I have no clue about what can be happening. I do not know whether can be related...Which Gazebo version are you using? (we tested just with Gazebo 11) It is your Gazebo using the GPU properly?

**Comment by masskro0** [comment]
I'm also using the newest commit with Gazebo 11. I'm not sure whether my GPU is being used, but I get the following message:
```[__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia -6]: process started with pid [301788]```

I noticed that all topics are empty, e.g. ```/people```, ```/human_states``` and so on. I guess that some node hasn't started, or at least one specific node is not publishing anything.

**Comment by noeperez** [comment]
I have noticed that you have a missing node: /hunav_plugin (this is the Gazebo plugin in charge of communicating with the /hunav_agent_manager).   
Check the screen output when you run it. At some point that node dies in your case.

**Comment by masskro0** [comment]
I was only able to see the issue by enabling the ```verbose```option. I had problems with the ```boost``` library and got that sorted out by modifying the CMakeLists file. Now everything is working fine, even though I'm getting the error
```[gazebo_shared.cc:46] System is attempting to load a plugin, but detected an incorrect plugin type. Plugin filename[libgazebo_ros_state.so].```
which corresponds to issue #3
